# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f472b7e328af700fcde9a8efb8c64695e68ac99cfbe4e2dbca20dee8833f47c76a66b0cc190cf3d172019ce1a5a224f65f190e5954ee79bea146917d2545c272

test:
  secret_key_base: f9fb0f67c147eda203478e49c6f6f2eb33f6d284f4e52832c75100c741f984478ba6ecc1b2af71de533fbab8c69be5ba020a825c0d31e850901cef4a46378fa4

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
